/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["triggerOcr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items:bulk-reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkReject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items:bulk-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkPublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concepts/{conceptId}/items:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ssoToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/credentials/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id}/sections/{sectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["excludeSection"];
        trace?: never;
    };
    "/api/v1/sources/{sourceId}/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/items/{itemId}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gradeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["weeklyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/misconceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["misconceptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["due"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["concepts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concepts/{conceptId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForConcept"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SourceResponse: {
            /** Format: uuid */
            id: string;
            kind: string;
            title: string;
            status: string;
            failureReason?: string;
            /** Format: int32 */
            pageCount?: number;
            needsOcr: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ImportSourceRequest: {
            url?: string;
            html?: string;
            title?: string;
        };
        OcrTriggerResponse: {
            /** Format: uuid */
            jobId: string;
        };
        StartSessionRequest: {
            scopeKind: string;
            /** Format: uuid */
            scopeId?: string;
            goalKind: string;
            /** Format: int32 */
            goalValue: number;
        };
        ItemMeta: {
            /** Format: uuid */
            conceptId: string;
            /** Format: float */
            expectedSuccess: number;
        };
        NextItemResponse: {
            /** Format: uuid */
            itemId: string;
            type: string;
            stem: string;
            payload: unknown;
            meta: components["schemas"]["ItemMeta"];
        };
        SessionResponse: {
            /** Format: uuid */
            sessionId: string;
            scopeKind: string;
            /** Format: uuid */
            scopeId?: string;
            goalKind: string;
            /** Format: int32 */
            goalValue: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string;
            next?: components["schemas"]["NextItemResponse"];
        };
        SkipRequest: {
            /** Format: uuid */
            itemId: string;
            reason?: string;
        };
        SkipResponse: {
            next?: components["schemas"]["NextItemResponse"];
        };
        FinishSessionResponse: {
            /** Format: uuid */
            sessionId: string;
            /** Format: int32 */
            attemptCount: number;
            /** Format: float */
            accuracy: number;
            /** Format: int64 */
            durationMs: number;
        };
        SubmitAttemptRequest: {
            /** Format: uuid */
            itemId: string;
            response: unknown;
            /** Format: int32 */
            elapsedMs: number;
        };
        ErrorAnalysisResponse: {
            category: string;
            /** Format: float */
            confidence: number;
            note?: string;
        };
        EvidenceResponse: {
            quote: string;
            /** Format: uuid */
            sourceId: string;
            /** Format: uuid */
            chunkId: string;
            /** Format: int32 */
            page?: number;
        };
        FeedbackResponse: {
            correctResponse: unknown;
            explanation: string;
            chosenOptionRationale?: string;
            evidence?: components["schemas"]["EvidenceResponse"];
        };
        LearnerUpdateResponse: {
            /** Format: uuid */
            conceptId: string;
            /** Format: float */
            thetaBefore: number;
            /** Format: float */
            thetaAfter: number;
            /** Format: float */
            mastery: number;
            /** Format: date-time */
            nextDueAt: string;
        };
        SubmitAttemptResponse: {
            /** Format: int64 */
            attemptId: number;
            outcome: string;
            /** Format: float */
            score: number;
            feedback: components["schemas"]["FeedbackResponse"];
            errorAnalysis?: components["schemas"]["ErrorAnalysisResponse"];
            learnerUpdate: components["schemas"]["LearnerUpdateResponse"];
            next?: components["schemas"]["NextItemResponse"];
        };
        PendingAttemptResponse: {
            next?: components["schemas"]["NextItemResponse"];
        };
        BulkItemIdsRequest: {
            ids: string[];
        };
        ClozeBlank: {
            accepted: string[];
        };
        ClozePayload: components["schemas"]["ItemPayload"] & {
            template: string;
            blanks: components["schemas"]["ClozeBlank"][];
        };
        ItemPayload: unknown;
        ItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conceptId: string;
            type: string;
            stem: string;
            payload: components["schemas"]["ClozePayload"] | components["schemas"]["MatchingPayload"] | components["schemas"]["McMultiPayload"] | components["schemas"]["McSinglePayload"] | components["schemas"]["OrderingPayload"] | components["schemas"]["ShortAnswerPayload"] | components["schemas"]["TrueFalsePayload"];
            explanation: string;
            bloomLevel: string;
            status: string;
            /** Format: uuid */
            sourceChunkId: string;
            /** Format: int32 */
            sourceCharFrom: number;
            /** Format: int32 */
            sourceCharTo: number;
            /** Format: int32 */
            reportCount: number;
            generatedBy?: string;
            /** Format: date-time */
            createdAt: string;
        };
        MatchingItem: {
            id: string;
            text: string;
        };
        MatchingPair: {
            leftId: string;
            rightId: string;
        };
        MatchingPayload: components["schemas"]["ItemPayload"] & {
            left: components["schemas"]["MatchingItem"][];
            right: components["schemas"]["MatchingItem"][];
            pairs: components["schemas"]["MatchingPair"][];
            distractorsRight: components["schemas"]["MatchingItem"][];
        };
        McMultiPayload: components["schemas"]["ItemPayload"] & {
            options: components["schemas"]["Option"][];
            shuffle: boolean;
        };
        McSinglePayload: components["schemas"]["ItemPayload"] & {
            options: components["schemas"]["Option"][];
            shuffle: boolean;
        };
        Option: {
            id: string;
            text: string;
            correct: boolean;
            rationale: string;
            misconceptionCategory?: string;
        };
        OrderingElement: {
            id: string;
            text: string;
        };
        OrderingPayload: components["schemas"]["ItemPayload"] & {
            elements: components["schemas"]["OrderingElement"][];
            correctOrder: string[];
            partialCredit: boolean;
        };
        RubricCriterion: {
            criterion: string;
            /** Format: int32 */
            points: number;
        };
        ShortAnswerPayload: components["schemas"]["ItemPayload"] & {
            rubric: components["schemas"]["RubricCriterion"][];
            referenceAnswer: string;
        };
        TrueFalsePayload: components["schemas"]["ItemPayload"] & {
            statement: string;
            answer: boolean;
            rationale: string;
        };
        ReportItemRequest: {
            reason: string;
            comment?: string;
        };
        GenerateItemsRequest: {
            /** Format: int32 */
            count: number;
            types: string[];
        };
        GenerateItemsResponse: {
            /** Format: uuid */
            jobId: string;
        };
        SsoTokenRequest: {
            /** @enum {string} */
            provider: "GOOGLE" | "GITHUB";
            code: string;
            codeVerifier: string;
            redirectUri: string;
        };
        TokenResponse: {
            accessToken: string;
            refreshToken: string;
            tokenType: string;
            /** Format: int64 */
            expiresIn: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CreateCredentialRequest: {
            /** @enum {string} */
            provider: "OPENAI" | "ANTHROPIC" | "GOOGLE" | "AZURE" | "OPENROUTER" | "OLLAMA";
            apiKey: string;
            baseUrl?: string;
            label?: string;
        };
        CredentialResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            provider: "OPENAI" | "ANTHROPIC" | "GOOGLE" | "AZURE" | "OPENROUTER" | "OLLAMA";
            label?: string;
            keyHint: string;
            baseUrl?: string;
            region?: string;
            status: string;
            /** Format: date-time */
            lastVerifiedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        VerifyCredentialResponse: {
            status: string;
            message: string;
            /** Format: date-time */
            lastVerifiedAt?: string;
        };
        ExcludeSectionRequest: {
            excluded: boolean;
        };
        SectionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId?: string;
            /** Format: int32 */
            ordinal: number;
            /** Format: int32 */
            level: number;
            title: string;
            excluded: boolean;
        };
        SourcePageResponse: {
            items: components["schemas"]["SourceResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
        };
        ConceptResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            summary: string;
            /** Format: int32 */
            frequency: number;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        GradeStatusResponse: {
            status: string;
            /** Format: int64 */
            attemptId?: number;
            outcome?: string;
            /** Format: float */
            score?: number;
            feedback?: components["schemas"]["FeedbackResponse"];
            errorAnalysis?: components["schemas"]["ErrorAnalysisResponse"];
            learnerUpdate?: components["schemas"]["LearnerUpdateResponse"];
            error?: string;
        };
        WeeklyReportGapResponse: {
            /** Format: uuid */
            conceptId: string;
            conceptName: string;
            /** Format: float */
            mastery: number;
        };
        WeeklyReportResponse: {
            topGaps: components["schemas"]["WeeklyReportGapResponse"][];
            recommendedFocus?: components["schemas"]["WeeklyReportGapResponse"];
        };
        ProgressOverviewResponse: {
            /** Format: int32 */
            conceptCount: number;
            /** Format: float */
            averageMastery: number;
            /** Format: int32 */
            dueCount: number;
        };
        MisconceptionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conceptId: string;
            category: string;
            /** Format: int32 */
            occurrences: number;
            flagged: boolean;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
        };
        ConceptProgressResponse: {
            /** Format: uuid */
            conceptId: string;
            /** Format: float */
            theta: number;
            /** Format: float */
            mastery: number;
            state: string;
            /** Format: int32 */
            reps: number;
            /** Format: int32 */
            lapses: number;
            /** Format: date-time */
            dueAt?: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName?: string;
            locale: string;
            plan: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: date-time */
            createdAt: string;
        };
        ItemPageResponse: {
            items: components["schemas"]["ItemResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
        };
        QuotaInfo: {
            plan: string;
            /** Format: int64 */
            limitMicros?: number;
            /** Format: int64 */
            usedMicros: number;
            exceeded: boolean;
        };
        UsageBreakdownEntry: {
            task: string;
            /** Format: int64 */
            costMicros: number;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
        };
        UsageSummaryResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: int64 */
            totalInputTokens: number;
            /** Format: int64 */
            totalOutputTokens: number;
            /** Format: int64 */
            totalCostMicros: number;
            topCostDrivers: components["schemas"]["UsageBreakdownEntry"][];
            quota: components["schemas"]["QuotaInfo"];
        };
        ProviderInfo: {
            /** @enum {string} */
            id: "OPENAI" | "ANTHROPIC" | "GOOGLE" | "AZURE" | "OPENROUTER" | "OLLAMA";
            displayName: string;
            requiresBaseUrl: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourcePageResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/json": components["schemas"]["ImportSourceRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    triggerOcr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OcrTriggerResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    skip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkipResponse"];
                };
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinishSessionResponse"];
                };
            };
        };
    };
    submitAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAttemptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitAttemptResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PendingAttemptResponse"];
                };
            };
        };
    };
    bulkReject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkItemIdsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"][];
                };
            };
        };
    };
    bulkPublish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkItemIdsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportItemRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conceptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateItemsRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerateItemsResponse"];
                };
            };
        };
    };
    ssoToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredentialResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredentialResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VerifyCredentialResponse"];
                };
            };
        };
    };
    excludeSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExcludeSectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConceptResponse"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    sections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SectionResponse"][];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    next: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NextItemResponse"];
                };
            };
        };
    };
    gradeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GradeStatusResponse"];
                };
            };
        };
    };
    weeklyReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeeklyReportResponse"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgressOverviewResponse"];
                };
            };
        };
    };
    misconceptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MisconceptionResponse"][];
                };
            };
        };
    };
    due: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConceptProgressResponse"][];
                };
            };
        };
    };
    concepts: {
        parameters: {
            query: {
                sourceId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConceptProgressResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reviewQueue: {
        parameters: {
            query?: {
                status?: "DRAFT" | "PUBLISHED" | "REJECTED" | "RETIRED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemPageResponse"];
                };
            };
        };
    };
    listForConcept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conceptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"][];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsageSummaryResponse"];
                };
            };
        };
    };
    providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProviderInfo"][];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
